### ISSUE TITLE
USER STORY: Love Running 3

### ISSUE THREAD

**Issue by CharlB96** [CharlB96/my-first-agile-project#5]
As a **site administrator** I can **easily edit and archive the polls** so that **they can stay up to date on a weekly/monthly basis**.

## Acceptance Criteria:
AC1: Make polls editable without too much hassle
AC2: Make the poll archive easily accessable and easily updated

## Tasks

- [ ] Task 1: Create default poll with placeholder text
- [ ] Task 2: Allow editing of the poll in both text and the number of options
- [ ] Task 3: Create archive page which will list all previous polls and have the administrator be able to update it.
